[theme]
primaryColor = "#0cc789"  # Button & accent color
backgroundColor = "#f5f7fa"  # Light grey background
secondaryBackgroundColor = "#e3e7ed"  # Sidebar & container background
textColor = "#212121"  # Dark text color